const {
  models: { Challenge },
} = require("../../server/db");

function getRandomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1) + min);
}

// 1 mental
// 2 physical
// 3 Sleep
// 4 food
// 5 misc
const dataChallenges = [
  {
    name: "5 minutes of meditation for two months",
    description:
      "Quick meditation can encourage a mentally clear and emotionally calm, stable state. You become better with practice.",
    image: "badges/picId-002.svg",
    goalType: "total",
    category: "mental",
    startDateTime: "03/15/2022",
    endDateTime: "05/15/2022",
    targetNumber: 30,
    targetUnit: "minutes",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "20 minutes of Yoga",
    description:
      "Light movement can reduce stress in your body and clear distracting or cluttered thoughts from your mind.",
    image: "badges/picId-003.svg",
    goalType: "daily",
    category: "physical",
    startDateTime: "04/10/2022",
    endDateTime: "05/10/2022",
    targetNumber: 20,
    targetUnit: "minutes",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Mid-day walk",
    description:
      "A walk outside helps reset and re-energize you mentally and physically for the rest of your work day.",
    image: "badges/picId-004.svg",
    goalType: "daily",
    category: "physical",
    startDateTime: "03/11/2022",
    endDateTime: "04/11/2022",
    targetNumber: 30,
    targetUnit: "minutes",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "10 minutes to stretch during the workday for a month",
    description:
      "Take small breaks for yourself to show care to your body throughout the day.",
    image: "badges/picId-005.svg",
    goalType: "total",
    category: "physical",
    startDateTime: "03/01/2022",
    endDateTime: "04/01/2022",
    targetNumber: 200,
    targetUnit: "minutes",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Drink 10 glasses of water a day for a week",
    description:
      "Hydration has a plethora of mental and physical benefits, that is attainable every day.",
    image: "badges/picId-006.svg",
    goalType: "daily",
    category: "food",
    startDateTime: "03/23/2022",
    endDateTime: "03/30/2022",
    targetNumber: 10,
    targetUnit: "glasses",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Go for a 30 minute mindful walk once a day",
    description:
      "Walking while observing your surroundings without looking at your phone or listening to music.",
    image: "badges/picId-007.svg",
    goalType: "daily",
    category: "physical",
    startDateTime: "04/01/2022",
    endDateTime: "05/01/2022",
    targetNumber: 30,
    targetUnit: "minutes",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Spend 360 minutes practicing your hobby this month",
    description:
      "What better way to boost your mood and mental wellness than to engage in a task you enjoy?",
    image: "badges/picId-008.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "02/15/2022",
    endDateTime: "03/15/2022",
    targetNumber: 360,
    targetUnit: "minutes",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Listen to 10,000 minutes of music",
    description:
      "Music has a powerful effect on the brain. Your favorite song can change your mindset and offer a mood boost.",
    image: "badges/picId-009.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "01/01/2022",
    endDateTime: "12/31/2022",
    targetNumber: 10000,
    targetUnit: "minutes",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Go to bed 30 minutes earlier than usual for a week",
    description:
      "There is nothing more important than sleep. An extra 30 minutes change alot. ",
    image: "badges/picId-010.svg",
    goalType: "daily",
    category: "sleep",
    startDateTime: "04/01/2022",
    endDateTime: "04/08/2022",
    targetNumber: 1,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Have a phone-free date night every month",
    description:
      "Unplug and recharge your body and mind. Putting down the phone can be a small step toward bettering your mental health. ",
    image: "badges/picId-011.svg",
    goalType: "total",
    category: "mental",
    startDateTime: "01/01/2022",
    endDateTime: "12/31/2022",
    targetNumber: 12,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Tell someone you love them every day this month",
    description:
      "Taking time to care for yourself with a rejuvenating activity has both short-term and long-term benefits for mental well-being.",
    image: "badges/picId-012.svg",
    goalType: "daily",
    category: "mental",
    startDateTime: "03/30/2021",
    endDateTime: "04/29/2021",
    targetNumber: 1,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Watch 5 comedy films",
    description:
      "Laughter is the best medicine. Watch a comedy special or your favorite funny movie.",
    image: "badges/picId-013.svg",
    goalType: "total",
    category: "mental",
    startDateTime: "10/01/2022",
    endDateTime: "11/01/2022",
    targetNumber: 5,
    targetUnit: "movies",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Get creative",
    description:
      "Creative expression, like drawing, painting, and writing, is linked to overall well-being.",
    image: "badges/picId-014.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "04/15/2022",
    endDateTime: "05/15/2022",
    targetNumber: 5,
    targetUnit: "art pieces",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Dance it out - 30 mins/day",
    description:
      "Dancing reduces levels of cortisol and increases endorphins, put on your favorite song and have a dance party for an instantly elevated mood. ",
    image: "badges/picId-015.svg",
    goalType: "daily",
    category: "physical",
    startDateTime: "04/10/2022",
    endDateTime: "05/10/2022",
    targetNumber: 30,
    targetUnit: "minutes",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Eat only dark chocolate for 3 months",
    description:
      "Flavonoids, caffeine, and theobromine in chocolate are thought to work together to improve alertness and mental skills.",
    image: "badges/picId-016.svg",
    goalType: "daily",
    category: "food",
    startDateTime: "04/11/2022",
    endDateTime: "07/11/2022",
    targetNumber: 1,
    targetUnit: "days",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Eat a banana 5x/week for a month",
    description:
      "Incorporate fruits, vegetables, nuts, and legumes into your diet to protect your brain. Sugar and processed foods can lead to inflammation throughout the body and brain. ",
    image: "badges/picId-017.svg",
    goalType: "total",
    category: "food",
    startDateTime: "03/31/2022",
    endDateTime: "04/30/2022",
    targetNumber: 20,
    targetUnit: "bananas",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Tidy up your space weekly for 6 months",
    description:
      "It is important that your space is a place you want to be in.",
    image: "badges/picId-018.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "03/30/2021",
    endDateTime: "09/30/2021",
    targetNumber: 24,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Spend 20 minutes a day learning a new skill for a month",
    description:
      "Learning a new skill requires a lot of focus which takes thoughts away from current stressors and can shift perspective. ",
    image: "badges/picId-019.svg",
    goalType: "total",
    category: "mental",
    startDateTime: "04/01/2022",
    endDateTime: "05/01/2022",
    targetNumber: 600,
    targetUnit: "minutes",
    difficulty: 4,
    isPrivate: "false",
  },
  {
    name: "10,000 steps a day for a week",
    description:
      "Being mindful of movement will help improve your cardiovascular health. ",
    image: "badges/picId-020.svg",
    goalType: "total",
    category: "physical",
    startDateTime: "04/15/2022",
    endDateTime: "04/22/2022",
    targetNumber: 10000,
    targetUnit: "steps",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Increase your vegetable intake",
    description: "Try one vegetable each day for a month.",
    image: "badges/picId-021.svg",
    goalType: "total",
    category: "food",
    startDateTime: "02/10/2022",
    endDateTime: "03/10/2022",
    targetNumber: 30,
    targetUnit: "vegetables",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "No added sugar for a week",
    description: "Replace your normal sugar treat with a healthy alternative.",
    image: "badges/picId-022.svg",
    goalType: "total",
    category: "food",
    startDateTime: "01/11/2022",
    endDateTime: "01/18/2022",
    targetNumber: 7,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "20 minutes of workout per day for a month",
    description:
      "Sign up for an online service and commit to one workout a day.",
    image: "badges/picId-023.svg",
    goalType: "daily",
    category: "physical",
    startDateTime: "02/28/2022",
    endDateTime: "03/30/2022",
    targetNumber: 20,
    targetUnit: "minutes",
    difficulty: 4,
    isPrivate: "false",
  },
  {
    name: "Take a time out ",
    description:
      "Set aside 15 minutes each day to be in a quiet environment. Sit still and practice your breathing 15.",
    image: "badges/picId-024.svg",
    goalType: "daily",
    category: "mental",
    startDateTime: "03/30/2022",
    endDateTime: "04/29/2022",
    targetNumber: 15,
    targetUnit: "minutes",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Reduce your monthly spending by $100",
    description: "Try to cut one thing every day.",
    image: "badges/picId-025.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "04/01/2021",
    endDateTime: "05/01/2021",
    targetNumber: 100,
    targetUnit: "dollars",
    difficulty: 4,
    isPrivate: "false",
  },
  {
    name: "Try pantry cooking",
    description:
      "Find creative ways to use the things you have in your pantry for all your meals. Only buy those grocery items that are perishable.",
    image: "badges/picId-026.svg",
    goalType: "total",
    category: "food",
    startDateTime: "04/15/2021",
    endDateTime: "05/15/2021",
    targetNumber: 20,
    targetUnit: "days",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Save $200 extra and add it to your emergency fund ",
    description:
      "Find creative ways to reduce your costs or to increase your income by little bits and add those together.",
    image: "badges/picId-027.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "04/10/2021",
    endDateTime: "05/10/2021",
    targetNumber: 200,
    targetUnit: "dollars",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Declutter",
    description:
      "Make a list of a few places you know you need to clear. Some places may take more than one day so break down those places into daily secions.",
    image: "badges/picId-028.svg",
    goalType: "daily",
    category: "misc",
    startDateTime: "04/11/2021",
    endDateTime: "05/11/2021",
    targetNumber: 30,
    targetUnit: "daily",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Create routine and stick to it",
    description:
      "Make a list of three things you will do every day and stick to it for 30 days.",
    image: "badges/picId-029.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "03/31/2022",
    endDateTime: "04/30/2022",
    targetNumber: 20,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Kindness every day for a month",
    description: "Do one small act of kindness every day for a month.",
    image: "badges/picId-030.svg",
    goalType: "total",
    category: "mental",
    startDateTime: "03/30/2022",
    endDateTime: "04/29/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 4,
    isPrivate: "false",
  },
  {
    name: "Photo of yourself",
    description:
      "Take a photo of yourself every day or take a photo of something that makes you happy.",
    image: "badges/picId-031.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "04/01/2022",
    endDateTime: "05/01/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "20,000 steps a day for a week",
    description: "20,000 is incredibly active. Strive for movement!",
    image: "badges/picId-020.svg",
    goalType: "daily",
    category: "physical",
    startDateTime: "04/15/2021",
    endDateTime: "05/15/2021",
    targetNumber: 20000,
    targetUnit: "steps",
    difficulty: 5,
    isPrivate: "false",
  },
  {
    name: "Try one new recipe a day for a week",
    description:
      "Start with the items you currently have in your freezer and refrigerator. Look for new recipes to try.",
    image: "badges/picId-033.svg",
    goalType: "total",
    category: "food",
    startDateTime: "04/10/2021",
    endDateTime: "04/18/2021",
    targetNumber: 7,
    targetUnit: "days",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Make a smoothie",
    description: "Try a lighter, and healthier breakfast",
    image: "badges/picId-034.svg",
    goalType: "total",
    category: "food",
    startDateTime: "04/11/2022",
    endDateTime: "05/11/2022",
    targetNumber: 30,
    targetUnit: "smoothies",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Dine out with a friend once a month for a year",
    description:
      "Make plans with a friend to eat at a new place. Mix up what friends or family you meet with and where you eat.",
    image: "badges/picId-035.svg",
    goalType: "total",
    category: "food",
    startDateTime: "01/01/2022",
    endDateTime: "01/01/2023",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Try something new",
    description:
      "Try a new wine, a new tea, a new dish, or just a new fruit or vegetable every day.",
    image: "badges/picId-036.svg",
    goalType: "total",
    category: "food",
    startDateTime: "03/30/2022",
    endDateTime: "04/29/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Draw a picture a day for a month ",
    description:
      "Make a list of 30 images to draw or 30 feelings/words to show through your drawings.",
    image: "badges/picId-037.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "04/01/2022",
    endDateTime: "05/01/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 4,
    isPrivate: "false",
  },
  {
    name: "Write a short story everyday for a month",
    description: "Have 30 short stories over the course of a month.",
    image: "badges/picId-038.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "04/15/2022",
    endDateTime: "05/15/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 4,
    isPrivate: "false",
  },
  {
    name: "Craft away for a week",
    description:
      "Do one craft project every day. Keep them simple or quick so that you can get done in less than an hour.",
    image: "badges/picId-039.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "04/10/2022",
    endDateTime: "04/17/2022",
    targetNumber: 7,
    targetUnit: "crafts",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Write a poem or haiku everyday for a week",
    description:
      "Use a list of feelings or words and turn them into a poem or haiku.",
    image: "badges/picId-040.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "04/11/2022",
    endDateTime: "07/18/2022",
    targetNumber: 7,
    targetUnit: "poems",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Keep a daily journal for a month",
    description: "write in your journal every morning or every evening.",
    image: "badges/picId-041.svg",
    goalType: "daily",
    category: "mental",
    startDateTime: "03/31/2022",
    endDateTime: "04/30/2022",
    targetNumber: 1,
    targetUnit: "entry",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Do your hair every day for a week",
    description:
      "Use new hair accessories or try putting your hair up in different ways (braids, buns, messy buns).",
    image: "badges/picId-042.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "03/30/2022",
    endDateTime: "04/6/2022",
    targetNumber: 7,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Dress up every day",
    description:
      "Dress like you are going to meet the love of your life or the President.",
    image: "badges/picId-043.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "04/01/2022",
    endDateTime: "05/01/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Positive affirmations everyday for a month",
    description:
      "Write down five truths you aim to achieve as “I am” statements..",
    image: "badges/picId-044.svg",
    goalType: "total",
    category: "mental",
    startDateTime: "04/15/2022",
    endDateTime: "05/15/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Burpee",
    description:
      "Practice doing as many Burpees as you can in 1 minute for month.",
    image: "badges/picId-045.svg",
    goalType: "total",
    category: "physical",
    startDateTime: "04/10/2022",
    endDateTime: "05/10/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Double Duty Move Your Booty",
    description:
      "Practice doing as many push-ups as you can every day for a month.",
    image: "badges/picId-046.svg",
    goalType: "total",
    category: "physical",
    startDateTime: "04/11/2022",
    endDateTime: "05/11/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 4,
    isPrivate: "false",
  },
  {
    name: "Fresh Exercise",
    description:
      "Do a new form of exercise when you workout instead of what you normally do.",
    image: "badges/picId-047.svg",
    goalType: "total",
    category: "physical",
    startDateTime: "03/31/2022",
    endDateTime: "04/30/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Lunge",
    description:
      "Practice doing as many lunges as you can in 1 minute for a month.",
    image: "badges/picId-048.svg",
    goalType: "total",
    category: "physical",
    startDateTime: "03/30/2022",
    endDateTime: "04/29/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Park and Walk",
    description: "Park farther away from the entrance of all places you drive.",
    image: "badges/picId-049.svg",
    goalType: "total",
    category: "physical",
    startDateTime: "04/01/2022",
    endDateTime: "05/01/2022",
    targetNumber: 20,
    targetUnit: "days",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Plank It",
    description: "Do a plank exercise for at least 1 minute for 30 days.",
    image: "badges/picId-050.svg",
    goalType: "total",
    category: "physical",
    startDateTime: "04/15/2022",
    endDateTime: "05/15/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 4,
    isPrivate: "false",
  },
  {
    name: "Push Up",
    description: "Do as many push ups as you can in 1 minute each day.",
    image: "badges/picId-051.svg",
    goalType: "total",
    category: "physical",
    startDateTime: "04/10/2022",
    endDateTime: "05/10/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 4,
    isPrivate: "false",
  },
  {
    name: "Sit Up",
    description:
      "Do as many sit-ups as you can comfortably do in one set each day.",
    image: "badges/picId-052.svg",
    goalType: "total",
    category: "physical",
    startDateTime: "04/11/2022",
    endDateTime: "05/11/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Squat",
    description: "Do as many squats as you can in 1 minute.",
    image: "badges/picId-053.svg",
    goalType: "total",
    category: "physical",
    startDateTime: "03/31/2021",
    endDateTime: "04/30/2021",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Step It Up",
    description:
      "Instead of the escalator or elevator, use the stairs everywhere.",
    image: "badges/picId-054.svg",
    goalType: "total",
    category: "physical",
    startDateTime: "03/30/2021",
    endDateTime: "04/29/2021",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Stretch It Out",
    description: "Stretch every day for at least 15 min a day for a week.",
    image: "badges/picId-055.svg",
    goalType: "daily",
    category: "physical",
    startDateTime: "04/01/2022",
    endDateTime: "05/01/2022",
    targetNumber: 15,
    targetUnit: "minutes",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Walk It Out",
    description: "Take a 15 minute walk every day for a week.",
    image: "badges/picId-056.svg",
    goalType: "daily",
    category: "physical",
    startDateTime: "04/15/2022",
    endDateTime: "05/15/2022",
    targetNumber: 15,
    targetUnit: "minutes",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "A Spoonful of Sugar-free",
    description: "No sugary foods or beverages.",
    image: "badges/picId-057.svg",
    goalType: "total",
    category: "food",
    startDateTime: "04/10/2022",
    endDateTime: "05/10/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Breakfast Boost",
    description: "Eat a healthy breakfast every day.",
    image: "badges/picId-058.svg",
    goalType: "total",
    category: "food",
    startDateTime: "04/11/2022",
    endDateTime: "05/11/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Fruited Up",
    description: "Eat three servings of fruit each day for a week.",
    image: "badges/picId-059.svg",
    goalType: "daily",
    category: "food",
    startDateTime: "03/31/2022",
    endDateTime: "04/07/2022",
    targetNumber: 3,
    targetUnit: "servings",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Get the Red Out",
    description: "Cut out processed and red meats from your diet for a month.",
    image: "badges/picId-060.svg",
    goalType: "total",
    category: "food",
    startDateTime: "03/30/2022",
    endDateTime: "04/29/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 5,
    isPrivate: "false",
  },
  {
    name: "Go for H2O",
    description:
      "Drink 64 oz of water each day before consuming other beverages.",
    image: "badges/picId-061.svg",
    goalType: "daily",
    category: "food",
    startDateTime: "04/01/2022",
    endDateTime: "05/01/2022",
    targetNumber: 64,
    targetUnit: "ounces",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Good Grainy",
    description: "Eat two servings of whole grains each day.",
    image: "badges/picId-062.svg",
    goalType: "daily",
    category: "food",
    startDateTime: "04/15/2021",
    endDateTime: "05/15/2021",
    targetNumber: 2,
    targetUnit: "servings",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Healthy Lunch",
    description:
      "Make a healthy lunch or snack substitution every day for a month.",
    image: "badges/picId-063.svg",
    goalType: "total",
    category: "food",
    startDateTime: "04/10/2021",
    endDateTime: "05/10/2021",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Maintain Don’t Gain",
    description: "Maintain or lose weight over the next 2 weeks.",
    image: "badges/picId-064.svg",
    goalType: "total",
    category: "food",
    startDateTime: "04/11/2022",
    endDateTime: "04/25/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Master Chef",
    description: "Prepare three healthy meals each week.",
    image: "badges/picId-065.svg",
    goalType: "total",
    category: "food",
    startDateTime: "03/31/2022",
    endDateTime: "04/30/2022",
    targetNumber: 12,
    targetUnit: "healthy meals",
    difficulty: 4,
    isPrivate: "false",
  },
  {
    name: "No Night Time Munchies",
    description: "No eating after 8 pm.",
    image: "badges/picId-066.svg",
    goalType: "total",
    category: "food",
    startDateTime: "03/30/2022",
    endDateTime: "04/29/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Plan to Eat Well",
    description: "Set and keep a specific nutrition goal.",
    image: "badges/picId-067.svg",
    goalType: "total",
    category: "food",
    startDateTime: "04/01/2022",
    endDateTime: "05/01/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Restaurant Rehab",
    description: "Make healthy food choices while eating out.",
    image: "badges/picId-068.svg",
    goalType: "total",
    category: "food",
    startDateTime: "04/15/2022",
    endDateTime: "05/15/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Shop and Eat Healthy",
    description: "Make healthy choices when shopping.",
    image: "badges/picId-069.svg",
    goalType: "total",
    category: "food",
    startDateTime: "04/10/2022",
    endDateTime: "05/10/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Snack Down",
    description:
      "Take out the snacks from your diet. It will force you to eat more consciously during breakfast, lunch and dinner.",
    image: "badges/picId-070.svg",
    goalType: "total",
    category: "food",
    startDateTime: "04/11/2022",
    endDateTime: "05/11/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Stop the Pop",
    description:
      "Soda is addictive and made up of artificial chemicals. Swap the soda for water.",
    image: "badges/picId-071.svg",
    goalType: "total",
    category: "food",
    startDateTime: "03/31/2022",
    endDateTime: "04/30/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Veg Out for a month",
    description: "Eat at least 3 servings of vegetables every day for a month.",
    image: "badges/picId-072.svg",
    goalType: "daily",
    category: "food",
    startDateTime: "03/30/2022",
    endDateTime: "04/29/2022",
    targetNumber: 3,
    targetUnit: "servings",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Watch the Plate",
    description: "Limit portion sizes every day.",
    image: "badges/picId-073.svg",
    goalType: "total",
    category: "food",
    startDateTime: "04/01/2021",
    endDateTime: "05/01/2021",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Cut it out",
    description:
      "Cut out processed foods for at least one meal each day for a month.",
    image: "badges/picId-074.svg",
    goalType: "daily",
    category: "food",
    startDateTime: "04/15/2021",
    endDateTime: "05/15/2021",
    targetNumber: 1,
    targetUnit: "meal",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Attitude of Gratitude",
    description: "Write down one thing for which you are grateful every day.",
    image: "badges/picId-075.svg",
    goalType: "daily",
    category: "mental",
    startDateTime: "04/10/2022",
    endDateTime: "05/10/2022",
    targetNumber: 1,
    targetUnit: "thing",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Breathe In Breathe Out",
    description: "Take 3 minutes a day to practice a deep breathing technique.",
    image: "badges/picId-076.svg",
    goalType: "daily",
    category: "mental",
    startDateTime: "04/11/2022",
    endDateTime: "05/11/2022",
    targetNumber: 3,
    targetUnit: "minutes",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Kindness Counts",
    description: "Do an act of kindness each day.",
    image: "badges/picId-077.svg",
    goalType: "total",
    category: "mental",
    startDateTime: "03/31/2022",
    endDateTime: "04/30/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "LOL - Make someone laugh daily",
    description: "Find humor in your day and share it with someone else.",
    image: "badges/picId-078.svg",
    goalType: "total",
    category: "mental",
    startDateTime: "03/30/2021",
    endDateTime: "04/29/2021",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "No Phone Zone",
    description: "Eliminate cell phone use anytime when driving.",
    image: "badges/picId-079.svg",
    goalType: "total",
    category: "mental",
    startDateTime: "04/01/2021",
    endDateTime: "05/01/2021",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Stress Down",
    description:
      "Complete a stress relieving activity for 10 minutes each day.",
    image: "badges/picId-080.svg",
    goalType: "daily",
    category: "mental",
    startDateTime: "04/15/2022",
    endDateTime: "05/15/2022",
    targetNumber: 10,
    targetUnit: "minutes",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Sweet Dreams",
    description: "Get at least 7 hours of sleep every day for a week.",
    image: "badges/picId-081.svg",
    goalType: "daily",
    category: "sleep",
    startDateTime: "04/10/2022",
    endDateTime: "04/18/2022",
    targetNumber: 7,
    targetUnit: "hours",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Unplug and Unwind",
    description:
      "Stop electronic device use one hour prior to bedtime every night.",
    image: "badges/picId-082.svg",
    goalType: "total",
    category: "mental",
    startDateTime: "04/11/2022",
    endDateTime: "05/11/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Cash No Card for a month",
    description:
      "Put your credit cards away and use cash for purchases to help limit spending.",
    image: "badges/picId-083.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "03/31/2022",
    endDateTime: "04/30/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Cut the Clutter",
    description:
      "Spend 5 minutes cleaning your work space, car, home or yard every day.",
    image: "badges/picId-084.svg",
    goalType: "daily",
    category: "misc",
    startDateTime: "03/30/2022",
    endDateTime: "04/29/2022",
    targetNumber: 5,
    targetUnit: "minutes",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Early 30 for a week",
    description: "Wake up 30 minutes earlier and do something productive.",
    image: "badges/picId-085.svg",
    goalType: "daily",
    category: "misc",
    startDateTime: "04/01/2022",
    endDateTime: "04/08/2022",
    targetNumber: 30,
    targetUnit: "minutes",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Organize!",
    description:
      "Gather all pertinent records for yourself and your family in one location. Spend 10 minutes a day organizing.",
    image: "badges/picId-086.svg",
    goalType: "daily",
    category: "misc",
    startDateTime: "04/15/2022",
    endDateTime: "05/15/2022",
    targetNumber: 10,
    targetUnit: "minutes",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Floss",
    description:
      "Floss everyday for a month. Cleaning between your teeth may help prevent cavities and gum disease.",
    image: "badges/picId-088.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "04/11/2022",
    endDateTime: "05/11/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Post your goals for the week",
    description:
      "Set a goal, write it down, post it where it is visible, and do it every day.",
    image: "badges/picId-089.svg",
    goalType: "total",
    category: "mental",
    startDateTime: "03/31/2022",
    endDateTime: "04/07/2022",
    targetNumber: 7,
    targetUnit: "days",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Stop the Buzz",
    description: "No more than one alcoholic beverage a day.",
    image: "badges/picId-090.svg",
    goalType: "total",
    category: "food",
    startDateTime: "03/30/2022",
    endDateTime: "04/29/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Watch your Wallet every week",
    description:
      "Track your daily spending and long it every week for three months (12 days).",
    image: "badges/picId-091.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "02/01/2022",
    endDateTime: "05/02/2022",
    targetNumber: 12,
    targetUnit: "days",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Sleep for at least 7 hours every day",
    description:
      "Aim to get at least 7-8 hours of sleep every day and see how your overall health improves!",
    image: "badges/picId-092.svg",
    goalType: "daily",
    category: "sleep",
    startDateTime: "04/15/2022",
    endDateTime: "05/15/2022",
    targetNumber: 7,
    targetUnit: "hours",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Try intermittent fasting for a week",
    description:
      "Intermittent fasting has been credited with improving overall health as well as helping with weight loss.",
    image: "badges/picId-093.svg",
    goalType: "total",
    category: "food",
    startDateTime: "04/10/2022",
    endDateTime: "04/18/2022",
    targetNumber: 7,
    targetUnit: "days",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Stretch or foam roll for 15 minutes for a week",
    description:
      "Give your tired and tight muscles a break with this gentle challenge.",
    image: "badges/picId-094.svg",
    goalType: "daily",
    category: "physical",
    startDateTime: "04/11/2022",
    endDateTime: "04/18/2022",
    targetNumber: 15,
    targetUnit: "minutes",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Give up one bad habit for a month",
    description:
      "You already know one bad habit you need to break up with. It can be done!",
    image: "badges/picId-095.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "03/31/2022",
    endDateTime: "04/30/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Walk for 30 minutes a day",
    description:
      "It is one of the gentlest forms of exercise and just about anyone can do it.",
    image: "badges/picId-096.svg",
    goalType: "daily",
    category: "physical",
    startDateTime: "03/30/2022",
    endDateTime: "04/29/2022",
    targetNumber: 30,
    targetUnit: "minutes",
    difficulty: 4,
    isPrivate: "false",
  },
  {
    name: "Stop complaining",
    description:
      "Complaining does not solve any issue and only spreads more negativity.",
    image: "badges/picId-097.svg",
    goalType: "total",
    category: "mental",
    startDateTime: "04/01/2022",
    endDateTime: "05/01/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Ready 20 minutes a day for a month",
    description: "Hopefully you can make it through a couple of books.",
    image: "badges/picId-098.svg",
    goalType: "daily",
    category: "misc",
    startDateTime: "04/15/2022",
    endDateTime: "05/15/2022",
    targetNumber: 20,
    targetUnit: "minutes",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Meditate daily",
    description:
      "Spend at least 15 minutes clearing your mind and focusing on your breathing.",
    image: "badges/picId-099.svg",
    goalType: "daily",
    category: "mental",
    startDateTime: "04/10/2022",
    endDateTime: "05/10/2022",
    targetNumber: 15,
    targetUnit: "minutes",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Create a goal or vision board and log daily",
    description:
      "Keep your board in a place where you can see it every day. It need only take a couple of minutes to log your progress or goals.",
    image: "badges/picId-100.svg",
    goalType: "total",
    category: "mental",
    startDateTime: "04/11/2021",
    endDateTime: "05/11/2021",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Follow a bedtime routine",
    description:
      "Stop eating two hours before bed, restrict device usage 30 minutes before bed or plan anything else to ensure a relaxing evening or full preperation for the next morning.",
    image: "badges/picId-101.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "03/31/2021",
    endDateTime: "04/30/2021",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Spend some time in nature",
    description:
      "Walk to a nearby park or grow and tend to a couple of plants on your window sill. Any little thing counts.",
    image: "badges/picId-102.svg",
    goalType: "total",
    category: "mental",
    startDateTime: "03/30/2021",
    endDateTime: "04/29/2021",
    targetNumber: 10,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Try a daily destress not involving a screen",
    description:
      "Give your eyes and mind a break from the endless scrolling and try something relaxing that does not involve a screen.",
    image: "badges/picId-103.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "04/01/2022",
    endDateTime: "05/01/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Read or write daily affirmations for a month",
    description:
      "Positive affirmations will lift your heart up increase the self love and your confidence will build up.",
    image: "badges/picId-104.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "04/15/2022",
    endDateTime: "05/15/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Avoid negative self talk",
    description:
      "Become your biggest cheerleader and see how your soul blossoms.",
    image: "badges/picId-105.svg",
    goalType: "total",
    category: "mental",
    startDateTime: "04/10/2022",
    endDateTime: "05/10/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Listen to an inspiring podcast everyday for a week",
    description:
      "There is something for everyone, no matter what interests you.",
    image: "badges/picId-106.svg",
    goalType: "daily",
    category: "misc",
    startDateTime: "04/02/2022",
    endDateTime: "04/09/2022",
    targetNumber: 1,
    targetUnit: "podcast",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Make a point of smiling every day",
    description:
      "Try injecting some light moments in your day, whatever works for you!",
    image: "badges/picId-107.svg",
    goalType: "total",
    category: "mental",
    startDateTime: "03/31/2022",
    endDateTime: "04/30/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Track your spending over the course of a month",
    description:
      "A great first step towards creating financial discipline. Track your expenditures and income for a month will make you aware of your habits.",
    image: "badges/picId-108.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "03/30/2022",
    endDateTime: "04/29/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Create and stick to a budget",
    description:
      "If you have a decent handle on what your current expenses and income looks like, take it step further and set a budget for yourself.",
    image: "badges/picId-109.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "04/01/2022",
    endDateTime: "05/01/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Try a 30 day shopping ban",
    description:
      "Get specific about what is banned and what exceptions you are going to make.",
    image: "badges/picId-110.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "04/15/2022",
    endDateTime: "05/15/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 4,
    isPrivate: "false",
  },
  {
    name: "Learn a new language",
    description:
      "Get the hang of the basics, there are great apps for learning a new language.",
    image: "badges/picId-111.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "04/10/2022",
    endDateTime: "05/10/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 5,
    isPrivate: "false",
  },
  {
    name: "Learn a few card magic tricks",
    description: "This will make you a party favorite pretty soon!",
    image: "badges/picId-112.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "04/11/2022",
    endDateTime: "05/11/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Make a short video every day for a month",
    description:
      "It does not have to be a lengthy one, just create content for an audience or just yourself.",
    image: "badges/picId-113.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "03/31/2022",
    endDateTime: "04/30/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Watch a TED TALK every day for a month",
    description:
      "By the end of the challenge, you will likely find yourself buzzing with ideas on how to improve your life!",
    image: "badges/picId-114.svg",
    goalType: "daily",
    category: "misc",
    startDateTime: "03/30/2022",
    endDateTime: "04/29/2022",
    targetNumber: 1,
    targetUnit: "TED Talk",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Set your 3 priorities for each day",
    description:
      "Having a daily list of important tasks can drastically improve your productivity.",
    image: "badges/picId-115.svg",
    goalType: "daily",
    category: "misc",
    startDateTime: "04/01/2022",
    endDateTime: "05/01/2022",
    targetNumber: 3,
    targetUnit: "priorities",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Give away/donate one thing every day for a week",
    description:
      "Keep a box out in plain sight and over the course of 7 days, fill it with things that you no longer need.",
    image: "badges/picId-116.svg",
    goalType: "daily",
    category: "misc",
    startDateTime: "04/15/2022",
    endDateTime: "04/22/2022",
    targetNumber: 1,
    targetUnit: "thing",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Create and commit to a meal plan for two months",
    description:
      "Eat healthy, avoid wasting food and save time when cooking. Remember to leave a bit of room for spontaneity.",
    image: "badges/picId-117.svg",
    goalType: "total",
    category: "food",
    startDateTime: "04/10/2022",
    endDateTime: "06/10/2022",
    targetNumber: 60,
    targetUnit: "days",
    difficulty: 4,
    isPrivate: "false",
  },
  {
    name: "Make your bed every day for 30 days",
    description: "Make it a part of your morning routine!",
    image: "badges/picId-118.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "04/11/2022",
    endDateTime: "05/11/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Reach out to one new person every day for a month",
    description:
      "Reach out to new people via Instagram, Twitter, emails. For social or for business, just do something every day that puts yourself out there.",
    image: "badges/picId-120.svg",
    goalType: "daily",
    category: "misc",
    startDateTime: "03/30/2022",
    endDateTime: "04/29/2022",
    targetNumber: 1,
    targetUnit: "person",
    difficulty: 5,
    isPrivate: "false",
  },
  {
    name: "Post an Instagram story at least once a day for a month",
    description:
      "It is a fantastic way to connect with your audience. Get comfortable talking to your followers and build a better relationship with them.",
    image: "badges/picId-121.svg",
    goalType: "daily",
    category: "misc",
    startDateTime: "04/01/2022",
    endDateTime: "05/01/2022",
    targetNumber: 1,
    targetUnit: "post",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Publish one post a day on your blog or Instagram or YouTube for a month",
    description:
      "Creating quality content takes a lot of time and effort, plan for this challenge and it can be done!",
    image: "badges/picId-122.svg",
    goalType: "daily",
    category: "misc",
    startDateTime: "04/15/2021",
    endDateTime: "05/15/2021",
    targetNumber: 1,
    targetUnit: "post",
    difficulty: 4,
    isPrivate: "false",
  },
  {
    name: "Eat at least one meal together with your partner/family a day for a month",
    description:
      "Coming together at meal times is one of the best ways to connect with your partner/family on a daily basis.",
    image: "badges/picId-123.svg",
    goalType: "daily",
    category: "misc",
    startDateTime: "04/10/2021",
    endDateTime: "05/10/2021",
    targetNumber: 1,
    targetUnit: "meal",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Write a 10 love notes to your partner or child",
    description: "Small love notes brighten up your partner or child!",
    image: "badges/picId-125.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "03/31/2022",
    endDateTime: "04/30/2022",
    targetNumber: 10,
    targetUnit: "notes",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Participate in your partner’s hobby for 10 hours this month",
    description:
      "Show active interest in their hobby, show up, and let them know that their interests matter to you as well.",
    image: "badges/picId-126.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "03/30/2022",
    endDateTime: "04/29/2022",
    targetNumber: 10,
    targetUnit: "hours",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Set up 30 surprises for your partner",
    description:
      "This does not have to be a big thing. Get creative with your ideas. Buy their favorite bottle of wine. Cook their favorite meal.",
    image: "badges/picId-127.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "04/01/2022",
    endDateTime: "05/01/2022",
    targetNumber: 30,
    targetUnit: "surprises",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Brush your teeth for two minutes twice a day",
    description:
      "It iss so easy and painless but so very hard to do well. Dental hygiene is more important than we realize.",
    image: "badges/picId-128.svg",
    goalType: "daily",
    category: "misc",
    startDateTime: "04/15/2022",
    endDateTime: "05/15/2022",
    targetNumber: 4,
    targetUnit: "minutes",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Floss every day",
    description:
      "Floss thoroughly every day. Cleaning between your teeth may help prevent cavities and gum disease.",
    image: "badges/picId-129.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "04/10/2022",
    endDateTime: "05/10/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Take your vitamins daily",
    description:
      "All have nutritional deficiencies, especially if our diets are not perfect.",
    image: "badges/picId-130.svg",
    goalType: "total",
    category: "food",
    startDateTime: "04/11/2022",
    endDateTime: "05/11/2022",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Do brain 10 mins of training exercises daily for a month",
    description:
      "Brain training is to push your brain to the point of frustration so that your neural connections strengthen. It can be incredibly difficult but pick an app and commit to doing the exercises.",
    image: "badges/picId-131.svg",
    goalType: "daily",
    category: "mental",
    startDateTime: "03/31/2022",
    endDateTime: "04/30/2022",
    targetNumber: 10,
    targetUnit: "minutes",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Detox your house",
    description:
      "Our houses are filled with toxic and synthetic chemicals. Over the next 30 days, do a home makeover and replace your regular household items with organic, natural ones. ",
    image: "badges/picId-132.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "03/30/2021",
    endDateTime: "04/29/2021",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Take a cold shower in the morning",
    description:
      "When you get up in the morning, head for the shower and turn it to cold. There are many health benefits of taking cold showers.",
    image: "badges/picId-133.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "04/01/2021",
    endDateTime: "05/01/2021",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "Bike 50 miles a week for a month",
    description:
      "Get on your bike and ride every day. Bike to work, bike around town or on hills or on trails.",
    image: "badges/picId-134.svg",
    goalType: "total",
    category: "physical",
    startDateTime: "04/15/2021",
    endDateTime: "05/15/2021",
    targetNumber: 200,
    targetUnit: "miles",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Cimb 1000 steps for a month",
    description: "For 30 days, refuse to use the elevator.",
    image: "badges/picId-135.svg",
    goalType: "total",
    category: "physical",
    startDateTime: "04/10/2021",
    endDateTime: "05/10/2021",
    targetNumber: 1000,
    targetUnit: "steps",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Whole body challenges for 30 days",
    description:
      "Strenghtening one body part can be boring so find something, anything, to do daily for 30 days.",
    image: "badges/picId-136.svg",
    goalType: "total",
    category: "physical",
    startDateTime: "04/11/2021",
    endDateTime: "05/11/2021",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Brainstorm daily for a month",
    description:
      "This is an easy and fun way to train yourself to think more creatively.",
    image: "badges/picId-137.svg",
    goalType: "total",
    category: "mental",
    startDateTime: "03/31/2021",
    endDateTime: "04/30/2021",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "Clean up your digital clutter everyday",
    description:
      "Work to clean up digital clutter: your email, your photos, your movies, your social media, passwords, documents.",
    image: "badges/picId-138.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "03/30/2021",
    endDateTime: "04/29/2021",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "Check email once a day",
    description:
      "A distraction and a time drain. Turn your email off on your phone and mobile devices and pick one time during the day to read and respond to emails. ",
    image: "badges/picId-139.svg",
    goalType: "total",
    category: "misc",
    startDateTime: "04/01/2021",
    endDateTime: "05/01/2021",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 4,
    isPrivate: "false",
  },
  {
    name: "No cussing",
    description: "Because, well shit. Oh shit. I just said shit. Shit.",
    image: "badges/picId-140.svg",
    goalType: "total",
    category: "mental",
    startDateTime: "04/15/2021",
    endDateTime: "05/15/2021",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "No devices in the bedroom ",
    description:
      "One of the most harmful ways to disrupt your sleep is to stare at a screen right before bedtime.",
    image: "badges/picId-141.svg",
    goalType: "total",
    category: "sleep",
    startDateTime: "04/10/2021",
    endDateTime: "05/10/2021",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 4,
    isPrivate: "false",
  },
  {
    name: "No fast food for a month",
    description:
      "A daily routine for some, it is addicting, cheap, and convenient, requiring a total, potentially very difficult shift in meal planning and preparation.",
    image: "badges/picId-142.svg",
    goalType: "total",
    category: "food",
    startDateTime: "04/11/2021",
    endDateTime: "05/11/2021",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "No news for a month",
    description:
      "No reading or watching the news. If something newsworthy happens, let someone else tell you about it. The news can be addicting and depressing.",
    image: "badges/picId-143.svg",
    goalType: "total",
    category: "mental",
    startDateTime: "03/31/2021",
    endDateTime: "04/30/2021",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 4,
    isPrivate: "false",
  },
  {
    name: "No social media for a week",
    description:
      "Usually done out of habit, social media is a productivity drain on society.",
    image: "badges/picId-144.svg",
    goalType: "total",
    category: "mental",
    startDateTime: "03/21/2021",
    endDateTime: "03/28/2021",
    targetNumber: 7,
    targetUnit: "days",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "No TV",
    description:
      "An hour or two of television every night is an hour or two we could spend doing more productive things.",
    image: "badges/picId-145.svg",
    goalType: "total",
    category: "mental",
    startDateTime: "04/01/2021",
    endDateTime: "05/01/2021",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 2,
    isPrivate: "false",
  },
  {
    name: "No caffeine",
    description:
      "You might get headaches from the caffeine withdrawals, so be prepared for the symptoms. Caffeine is a drug yet is never treated as such.",
    image: "badges/picId-146.svg",
    goalType: "total",
    category: "food",
    startDateTime: "04/15/2021",
    endDateTime: "05/15/2021",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 3,
    isPrivate: "false",
  },
  {
    name: "No gossiping for a month",
    description:
      "Gossip is very tempting yet harmful. It is to speak with the intent of eroding another reputation or image. Take a break from the negativity.",
    image: "badges/picId-147.svg",
    goalType: "total",
    category: "mental",
    startDateTime: "04/10/2021",
    endDateTime: "05/10/2021",
    targetNumber: 30,
    targetUnit: "days",
    difficulty: 1,
    isPrivate: "false",
  },
  {
    name: "No internet for a week",
    description:
      "No internet for a week. Everything used to be done offline such as banking, shopping, communicating, and working.",
    image: "badges/picId-149.svg",
    goalType: "total",
    category: "mental",
    startDateTime: "03/31/2021",
    endDateTime: "04/07/2021",
    targetNumber: 7,
    targetUnit: "days",
    difficulty: 5,
    isPrivate: "false",
  },
];

// Creating Challenges
async function challengeSeed() {
  //creating one stable challenge for testing that always maintains ID 1
  await Challenge.create({
    name: "300 minutes breathing exercise",
    description:
      "Taking deep breaths will create a sense of calm in the mind and body.",
    image: "badges/picId-001.svg",
    goalType: "total",
    category: "mental",
    startDateTime: "03/01/2021",
    endDateTime: "05/01/2021",
    targetNumber: 300,
    targetUnit: "minutes",
    difficulty: 1,
    isPrivate: "false",
  });
  await Challenge.create({
    name: "Run 10 miles a day",
    description:
      "Run run run. Exercising is good for heart health - go outside and get your legs moving!",
    image: "badges/picId-096.svg",
    goalType: "daily",
    category: "physical",
    startDateTime: "03/01/2021",
    endDateTime: "04/30/2021",
    targetNumber: 10,
    targetUnit: "miles",
    difficulty: 4,
    isPrivate: "false",
    goalType: "daily",
  });
  const challenges = await Promise.all(
    dataChallenges.map((challenge) =>
      Challenge.create({
        name: challenge.name,
        description: challenge.description,
        image: challenge.image,
        goalType: challenge.goalType,
        category: challenge.category,
        startDateTime: challenge.startDateTime,
        endDateTime: challenge.endDateTime,
        targetNumber: challenge.targetNumber,
        targetUnit: challenge.targetUnit,
        difficulty: challenge.difficulty,
        isPrivate: challenge.isPrivate,
      })
    )
  );

  const chalsPast = challenges.filter(
    (c) => new Date() >= new Date(c.endDateTime)
  );
  const ongoingChals = challenges.filter(
    (c) =>
      new Date() >= new Date(c.startDateTime) &&
      new Date() < new Date(c.endDateTime)
  );
  const chalsFuture = challenges.filter(
    (c) => new Date() < new Date(c.endDateTime)
  );

  console.log(
    `seeded ${challenges.length + 2} challenges - Past: ${
      chalsPast.length
    }, Ongoing: ${ongoingChals.length}, Future: ${chalsFuture.length}`
  );
  // console.log(`seeded ${moreChallenges.length} past challenges`);

  return challenges;
}

module.exports = challengeSeed;
