const dataChallenges = [
 {
  "id": 1,
  "name": "10 minutes breathing exercise",
  "description": "Focusing on your breathing and taking three deep breaths will create a sense of calm in the mind and body.",
  "image": "picId-001.svg",
  "type": "num",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": 10,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 2,
  "name": "5 minutes meditation",
  "description": "Being alone with your thoughts can seem daunting but even a quick meditation can encourage a mentally clear and emotionally calm, stable state. As with sport, you become better at meditation with practice.",
  "image": "picId-002.svg",
  "type": "num",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": 5,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 3,
  "name": "20 minutes Home Yoga Workout",
  "description": "Even light movement can reduce stress in your body and clear distracting or cluttered thoughts from your mind.",
  "image": "picId-003.svg",
  "type": "num",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": 20,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 4,
  "name": "Mid-day walk at lunch",
  "description": "A walk outside helps reset and re-energize you mentally and physically for the rest of your work day.",
  "image": "picId-004.svg",
  "type": "unit",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "05/11/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 5,
  "name": "10 minutes to stretch during the workday",
  "description": "Taking small breaks for yourself to show care to your body throughout the day helps build stamina and decreases feelings of burnout.",
  "image": "picId-005.svg",
  "type": "num",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": 10,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 6,
  "name": "Drink 10 glasses of water a day",
  "description": "Not only does hydration have a plethora of mental and physical benefits, but drinking more water gives you a healthy goal that is attainable every day if you maintain focus and stay mindful.",
  "image": "picId-006.svg",
  "type": "num",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": 10,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 7,
  "name": "Go for a mindful walk",
  "description": "Walking while observing your surroundings – without looking at your phone or listening to music – is a great exercise in being present.",
  "image": "picId-007.svg",
  "type": "unit",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 8,
  "name": "Spend time on a hobby",
  "description": "What better way to boost your mood and mental wellness than to engage in a task you enjoy?",
  "image": "picId-008.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 9,
  "name": "Listen to your favorite music",
  "description": "Music has a powerful effect on the brain. Your favorite song can change your mindset and offer a mood boost.",
  "image": "picId-009.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 10,
  "name": "Go to bed 30 minutes earlier than usual",
  "description": "There’s nothing more important than sleep. You’d be surprised what an extra 30 minutes can do. ",
  "image": "picId-010.svg",
  "type": "unit",
  "categoryId": "3",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "05/11/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 11,
  "name": "Have a phone-free night",
  "description": "Unplug and recharge your body and mind. Increased screen time has been correlated with increased levels of depression. Putting down the phone could be a small step toward bettering your mental health. ",
  "image": "picId-011.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 12,
  "name": "Practice self-care",
  "description": "Taking time to care for yourself with a rejuvenating activity has both short-term and long-term benefits for mental well-being.",
  "image": "picId-012.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 13,
  "name": "Have a laugh",
  "description": "Laughter is the best medicine. Watch a comedy special or your favorite funny movie.",
  "image": "picId-013.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 14,
  "name": "Get creative",
  "description": "Creative expression, like drawing, painting, and writing, is linked to overall well-being.",
  "image": "picId-014.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 15,
  "name": "Dance it out",
  "description": "Dancing reduces levels of cortisol and increases endorphins, so put on your favorite song and have a dance party for an instantly elevated mood. ",
  "image": "picId-015.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 16,
  "name": "Eat some dark chocolate",
  "description": "Flavonoids, caffeine, and theobromine in chocolate are thought to work together to improve alertness and mental skills.",
  "image": "picId-016.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "05/11/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 17,
  "name": "Eat a nutritious meal",
  "description": "Incorporate fruits, vegetables, foods rich in omega-3 fatty acids, nuts, and legumes into your diet to protect your brain. Sugar and processed foods can lead to inflammation throughout the body and brain, which may contribute to mood disorders, including anxiety and depression. ",
  "image": "picId-017.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 18,
  "name": "Tidy up your space",
  "description": "If the space in which you live and work is cluttered, your mind will also be cluttered! With so many of us working from home, it’s important that your space is a place you want to be.",
  "image": "picId-018.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 19,
  "name": "Learn a new skill",
  "description": "Learning a new skill requires a lot of focus which takes thoughts away from current stressors and can shift perspective. ",
  "image": "picId-019.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 20,
  "name": "8,000 steps a day",
  "description": "In an ideal world, the target for this should be 10,000 steps or more. But if you’re only about getting 1,500-2,000 steps a day right now, scaling up to 10,000 all of a sudden might feel a bit too hard. Aiming for 4,000 – 5,000 steps more than your current daily average should provide you a decent challenge.",
  "image": "picId-020.svg",
  "type": "num",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": 8000,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 21,
  "name": "Increase your vegetable intake",
  "description": "Try one new vegetable each day",
  "image": "picId-021.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 22,
  "name": "Decrease your sugar intake",
  "description": "Replace your normal sugar treat with a healthy alternative",
  "image": "picId-022.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "05/11/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 23,
  "name": "Start a fitness program",
  "description": "Sign up for an online service and commit to one workout a day",
  "image": "picId-023.svg",
  "type": "unit",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 24,
  "name": "Take a time out ",
  "description": "Set aside 15 minutes each day to be in a quiet environment. Sit still and practice breathing in for a count of ten and out for a count of 15",
  "image": "picId-024.svg",
  "type": "num",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": 15,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 25,
  "name": "Reduce your monthly spending by $100",
  "description": "Cut one thing each day (it doesn’t have to be cummulative)",
  "image": "picId-025.svg",
  "type": "num",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": 100,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 26,
  "name": "Try pantry cooking",
  "description": "Find creative ways to use the things you have in your pantry for all your meals. Only buy those grocery items that are perishable.",
  "image": "picId-026.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 27,
  "name": "Save $200 extra and add it to your emergency fund ",
  "description": "Find creative ways to reduce your costs or to increase your income by little bits and add those together",
  "image": "picId-027.svg",
  "type": "num",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": 200,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 28,
  "name": "Declutter",
  "description": "Make a list of 30 places you know you need to clear. Some places may take more than one day so break down those places into daily secions",
  "image": "picId-028.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "05/11/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 29,
  "name": "Create routine and stick to it",
  "description": "Make a list of three things you will do every day (that needs to be done) and stick to it for 30 days",
  "image": "picId-029.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 30,
  "name": "Kindness every day",
  "description": "Do one small act of kindness every day",
  "image": "picId-030.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 31,
  "name": "Photo of yourself",
  "description": "Take a photo of yourself every day or take a photo of something that makes you happy.",
  "image": "picId-031.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 32,
  "name": "Give a gift a day",
  "description": "Give away items others appreciate or set aside small gifts to give to random people or to send to friends. Keep it interesting and make the gifts from a Secret Pal.",
  "image": "picId-032.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 33,
  "name": "Try one new recipe a day",
  "description": "Start with the items you currently have in your freezer and refrigerator. Look for new recipes to try.",
  "image": "picId-033.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 34,
  "name": "Make a smoothie each day",
  "description": "This could be a great time to try out one of the delivery services that will send you what you need to make interesting new mixes.",
  "image": "picId-034.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "05/11/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 35,
  "name": "Dine out with a friend",
  "description": "Make plans with a friend to eat at a new place. Mix up what friends or family you meet with and where you eat. It doesn’t always have to be a sit down restaurant – maybe you eat at the park and bring sack lunches. Keep a record of your favorite parts of the meals if you want a bonus challenge.",
  "image": "picId-035.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 36,
  "name": "Try something new",
  "description": "Try a new wine, a new tea, a new dish, or just a new fruit or vegetable every day. You may discover flavors that you never knew you needed.",
  "image": "picId-036.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 37,
  "name": "Draw a picture a day ",
  "description": "Make a list of 30 images to draw or 30 feelings/words to show through your drawings.",
  "image": "picId-037.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 38,
  "name": "Write a short story",
  "description": "Have 30 images or writing posts to prompt a short story.",
  "image": "picId-038.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 39,
  "name": "Craft away",
  "description": "Do one craft project every day. Keep them simple or quick so that you can get done in less than an hour.",
  "image": "picId-039.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 40,
  "name": "Write a poem or haiku",
  "description": "Use the list of feelings or words and turn them into a poem or haiku instead of a drawing.",
  "image": "picId-040.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "05/11/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 41,
  "name": "Keep a journal ",
  "description": "Set a timer for five minutes and write in your journal every morning or every evening.",
  "image": "picId-041.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 42,
  "name": "Try a new hairstyle every day",
  "description": "Use new hair accessories or try putting your hair up in different ways (braids, buns, messy buns).",
  "image": "picId-042.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 43,
  "name": "Dress up every day",
  "description": "Dress like you are going to meet with the President (of the country or of your company).",
  "image": "picId-043.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 44,
  "name": "“I am” statement",
  "description": "Write down five truths you aim to achieve as “I am” statements. “I AM” healthy and fit. “I Am” a published author. “I am debt free.” Say your five truths in the mirror every day for thirty days.",
  "image": "picId-044.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 45,
  "name": "Burpee",
  "description": "Do as many Burpees as you can in 1 minute",
  "image": "picId-045.svg",
  "type": "unit",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 46,
  "name": "Double Duty Move Your Booty",
  "description": "Do as many push-ups as you can and then go for a 15 minute walk every day",
  "image": "picId-046.svg",
  "type": "unit",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "05/11/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 47,
  "name": "Fresh Exercise",
  "description": "Do a new form of exercise than what you normally do",
  "image": "picId-047.svg",
  "type": "unit",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 48,
  "name": "Lunge",
  "description": "Carefully do as many lunges as you can in 1 minute",
  "image": "picId-048.svg",
  "type": "unit",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 49,
  "name": "Park and Walk",
  "description": "Park farther away from the entrance of all places you drive",
  "image": "picId-049.svg",
  "type": "unit",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 50,
  "name": "Plank It",
  "description": "Do a plank exercise for at least 1 minute",
  "image": "picId-050.svg",
  "type": "unit",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 51,
  "name": "Push Up",
  "description": "Do as many push ups as you can in 1 minute each day",
  "image": "picId-051.svg",
  "type": "unit",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 52,
  "name": "Sit Up",
  "description": "Do as many sit-ups as you can comfortably do in one set each day",
  "image": "picId-052.svg",
  "type": "unit",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "05/11/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 53,
  "name": "Squat",
  "description": "Do as many squats as you can in 1 minute",
  "image": "picId-053.svg",
  "type": "unit",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 54,
  "name": "Step It Up",
  "description": "Instead of the escalator or elevator, use the stairs everywhere",
  "image": "picId-054.svg",
  "type": "unit",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 55,
  "name": "Stretch It Out",
  "description": "Stretch every day",
  "image": "picId-055.svg",
  "type": "unit",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 56,
  "name": "Walk It Out",
  "description": "Take a 15 minute walk every day",
  "image": "picId-056.svg",
  "type": "num",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": 15,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 57,
  "name": "A Spoonful of Sugar-free",
  "description": "No sugary foods or beverages",
  "image": "picId-057.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 58,
  "name": "Breakfast Boost",
  "description": "Eat a healthy breakfast every day",
  "image": "picId-058.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "05/11/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 59,
  "name": "Fruited Up",
  "description": "Eat three servings of fruit each day",
  "image": "picId-059.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 60,
  "name": "Get the Red Out",
  "description": "Cut out processed and red meats from your diet",
  "image": "picId-060.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 61,
  "name": "Go for H20",
  "description": "Drink 64 oz of water each day before consuming other beverages",
  "image": "picId-061.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 62,
  "name": "Good Grainy",
  "description": "Eat two servings of whole grains each day",
  "image": "picId-062.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 63,
  "name": "Healthy Lunch",
  "description": "Make a healthy lunch or snack substitution every day",
  "image": "picId-063.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 64,
  "name": "Maintain Don’t Gain",
  "description": "Maintain or lose weight over the next 2 weeks",
  "image": "picId-064.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "04/25/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 65,
  "name": "Master Chef",
  "description": "Prepare three healthy meals from the WellSteps recipe section each week",
  "image": "picId-065.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 66,
  "name": "No Night Time Munchies",
  "description": "No eating after 8 pm",
  "image": "picId-066.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 67,
  "name": "Plan to Eat Well",
  "description": "Set and keep a specific nutrition goal",
  "image": "picId-067.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 68,
  "name": "Restaurant Rehab",
  "description": "Use The Stop and Go Fast Food Guide to make healthy food choices",
  "image": "picId-068.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 69,
  "name": "Shop and Eat Healthy",
  "description": "Use The Stop and Go Grocery Guide to make healthy choices when shopping",
  "image": "picId-069.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 70,
  "name": "Snack Down",
  "description": "We snack in the morning, we snack in the afternoon, we pick on food when it’s around even if we’re not hungry. And usually, it’s not the healthiest of foods. If you’re a serial snacker (who favors the quick and easy), this is a challenge for you. Taking out the snacks from our diets forces us to eat more consciously during breakfast, lunch and dinner.",
  "image": "picId-070.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "05/11/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 71,
  "name": "Stop the Pop",
  "description": "Soda is a stimulant. It is also addictive. And made up of all sorts of artificial things which means that it has zero nutritional value. Swap the soda for water and you will not only save money, but you just might lose a few pounds too",
  "image": "picId-071.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 72,
  "name": "Veg Out",
  "description": "Eat at least 3 servings of vegetables every day",
  "image": "picId-072.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 73,
  "name": "Watch the Plate",
  "description": "Limit portion sizes every day",
  "image": "picId-073.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 74,
  "name": "White Out",
  "description": "Cut out processed foods for at least one meal each day",
  "image": "picId-074.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 75,
  "name": "Attitude of Gratitude",
  "description": "Write down one thing for which you are grateful every day",
  "image": "picId-075.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 76,
  "name": "Breathe In Breathe Out",
  "description": "Take 3 minutes a day to practice a deep breathing technique",
  "image": "picId-076.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "05/11/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 77,
  "name": "Kindness Counts",
  "description": "Do an act of kindness each day",
  "image": "picId-077.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 78,
  "name": "LOL",
  "description": "Find humor in your day and share it with someone else",
  "image": "picId-078.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 79,
  "name": "No Phone Zone",
  "description": "Eliminate cell phone use anytime when driving",
  "image": "picId-079.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 80,
  "name": "Stress Down",
  "description": "Complete a stress relieving activity for 10 minutes each day",
  "image": "picId-080.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 81,
  "name": "Sweet Dreams",
  "description": "Get 7-8 hours of sleep every day",
  "image": "picId-081.svg",
  "type": "unit",
  "categoryId": null,
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 82,
  "name": "Unplug and Unwind",
  "description": "Stop electronic device use one hour prior to bedtime every night",
  "image": "picId-082.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "05/11/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 83,
  "name": "Cash No Card",
  "description": "Put your credit cards away and use cash for purchases",
  "image": "picId-083.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 84,
  "name": "Cut the Clutter",
  "description": "Spend 5 minutes cleaning your work space, car, home or yard every day",
  "image": "picId-084.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 85,
  "name": "Early 30",
  "description": "Wake up 30 minutes earlier and do something productive",
  "image": "picId-085.svg",
  "type": "num",
  "categoryId": "3",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": 30,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 86,
  "name": "Emergency Prep Records",
  "description": "Gather all pertinent records for yourself and your family in one location",
  "image": "picId-086.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 87,
  "name": "72-Hour Kit",
  "description": "Create an emergency 72 hour kit",
  "image": "picId-087.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 88,
  "name": "Floss Like a Boss",
  "description": "Floss every day",
  "image": "picId-088.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "05/11/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 89,
  "name": "Go for the Goal",
  "description": "Set a goal, write it down, post it where it is visible, and do it every day",
  "image": "picId-089.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 90,
  "name": "Stop the Buzz",
  "description": "No more than one alcoholic beverage a day",
  "image": "picId-090.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 91,
  "name": "Watch your Wallet",
  "description": "Track your daily spending",
  "image": "picId-091.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 92,
  "name": "Sleep for at least 7 hours every day",
  "description": "The way I look at it, sleep is one of the three pillars that contribute to healthy living. Aim to get at least 7-8 hours of sleep every day for 30 days and see how your overall health improves!",
  "image": "picId-092.svg",
  "type": "num",
  "categoryId": "3",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": 7,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 93,
  "name": "Try intermittent fasting",
  "description": "Intermittent fasting has been credited with improving overall health as well as helping with weight loss. There are plenty of ways to do intermittent fasting but if you’re an absolute beginner, you could start with a 12 hours of fasting + 12 hours of eating plan (12:12), and move up to 16:8 or even 18:6.  ",
  "image": "picId-093.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 94,
  "name": "Stretch or foam roll for 15 minutes",
  "description": "Give your tired and tight muscles a break with this gentle challenge.",
  "image": "picId-094.svg",
  "type": "num",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "05/11/2022",
  "targetNumber": 15,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 95,
  "name": "Give up one bad habit",
  "description": "I am pretty sure you already know what’s that one bad habit of yours that you REALLY need to break up with. I’m currently on day 114 of a no cola streak, so yes, I know it isn’t easy, but I also know that it can be done!",
  "image": "picId-095.svg",
  "type": "unit",
  "categoryId": "3",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 96,
  "name": "Walk daily for 30 minutes",
  "description": "Walking is probably my favorite form of exercise, and I’ve been missing my daily walks lately. It is one of the gentlest forms of exercise and just about anyone can do it.",
  "image": "picId-096.svg",
  "type": "num",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": 30,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 97,
  "name": "Stop complaining",
  "description": "This is a hard one, but it’s going to be definitely worth your while if you want to be happier. Complaining does not solve any issue and only spreads more negativity. Try giving it a break for 30 days to see how it makes a difference to your mental peace.",
  "image": "picId-097.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 98,
  "name": "Ready 20 pages a day",
  "description": "Bonus points if you make it non-fiction!",
  "image": "picId-098.svg",
  "type": "num",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": 20,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 99,
  "name": "Meditate daily",
  "description": "Ooooh, I know this is a tough one. And trust me, I’ve struggled with it in the past as well. But seriously though, meditation is the new black! Rather, it always was, but we seem to be waking up to its benefits only in the past few years. There are plenty of apps that can help you to create this habit.",
  "image": "picId-099.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 100,
  "name": "Create a vision board and reflect on it daily",
  "description": "Keep your vision board in a place where you can see it every day, and create a visualization routine. It need only take a couple of minutes, or you could even add a journaling ritual around it. The idea is to make your vision visible so that you can take inspired action to make your dreams come true.",
  "image": "picId-100.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "05/11/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 101,
  "name": "Follow a bedtime routine",
  "description": "No matter what you add or don’t add to your night-time routine, you better make sure that “take off makeup” definitely features on this list!",
  "image": "picId-101.svg",
  "type": "unit",
  "categoryId": "3",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 102,
  "name": "Spend some time in nature",
  "description": "I don’t think I need to sell you the benefits of spending time in nature! Get creative if you don’t live right next to a lush forest. Walk to a nearby park. Grow and tend to a couple of plants on your window sill. Every little thing counts.",
  "image": "picId-102.svg",
  "type": "unit",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 103,
  "name": "Try a daily destress solution which does not involve a screen",
  "description": "Give your eyes (and mind) a break from the endless scrolling and try something that does not involve a screen.",
  "image": "picId-103.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 104,
  "name": "Read or write daily affirmations",
  "description": "Positive affirmations will lift your heart up, and the more you practice repeating affirmations to yourself, the more self love and confidence you will build up.",
  "image": "picId-104.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 105,
  "name": "Avoid negative self talk",
  "description": "Give your inner mean girl a rest and try making her an ally instead. Become your biggest cheerleader over the course of 30 days and see how your soul blossoms.",
  "image": "picId-105.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 106,
  "name": "Listen to an inspiring podcast",
  "description": "Podcasts have been one of my favorite discoveries this year, and I love how there is something for everyone, no matter what your interests. ",
  "image": "picId-106.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "05/11/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 107,
  "name": "Laugh every day",
  "description": "This SHOULD NOT really have to be a 30 day challenge but I know that life can be hard from time to time. Try injecting some light moments in your day – watch a couple of silly videos or an episode of your favorite comedy show. Call up a friend who always cracks you up. If you’ve got kids, get in some tickle time with them. Whatever works for you!",
  "image": "picId-107.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 108,
  "name": "Track your spending",
  "description": "Think of this as a first step towards creating financial discipline. Tracking your expenditures (and income) for a month will make you aware of your habits. Who knows, it might even tempt you out of your weekly Friday evening shopping haul!",
  "image": "picId-108.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 109,
  "name": "Create and stick to a budget",
  "description": "If you have a decent handle on what your current expenses and income looks like, take it step further and set a budget for yourself for 30 days. If you manage to stick to it, you’ll end up feeling like a badass + have some savings to boast of! Ka-ching!",
  "image": "picId-109.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 110,
  "name": "Try a shopping ban",
  "description": "I’ve tried a 30-day shopping ban once, and I did not find it all that hard, tbh. But you definitely need to plan for this! Get specific about what is banned and what exceptions you’re going to make. Since it’s only 30 days, ideally, everything apart from essentials should be on the banned list.",
  "image": "picId-110.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 111,
  "name": "Learn a new language",
  "description": "Okay sure, you may not learn a new language completely in 30 days, but you’ll surely get a hang of the basics in that period. Babbel and Duolingo are two great apps for learning a new language.",
  "image": "picId-111.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 112,
  "name": "Learn a few card magic tricks",
  "description": "This will make you a party favourite pretty soon!",
  "image": "picId-112.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "05/11/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 113,
  "name": "Make a short video every day",
  "description": "If you typically take a lot of photos every day, switch things up and shoot video instead. It does not have to be a lengthy one. The 1 Second Everyday app is a fantastic starting place. Record a one-second video for each day, and then use the app to put it all together to create a 30-second video! ",
  "image": "picId-113.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 114,
  "name": "Watch a TED TALK every day",
  "description": "This one shouldn’t be too difficult really, given the number of TED talks that are there! By the end of the challenge, you will likely find yourself buzzing with ideas on how to improve your life!",
  "image": "picId-114.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 115,
  "name": "Set your top 3-5 priorities for each day",
  "description": "On the days that I do this, I end up having an extremely focused and productive day. Which begs the question that why don’t I do it every day, but then again, I digress. Anyway, having a daily list of MITs (Most Important Tasks) could be a game-changer for you, so why not use a 30 day challenge to make it a habit?",
  "image": "picId-115.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 116,
  "name": "Give away/donate one thing every day ",
  "description": "If you’ve been caught by the minimalism bug, this could be a good way to initiate yourself. Keep a box out in plain sight and over the course of 30 days, fill it with things from around the house that you would want to give away.",
  "image": "picId-116.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 117,
  "name": "Live by a meal plan",
  "description": "This could be a great way of ensuring that you’re eating healthy + not wasting food items. If you plan to do this, my suggestion would be to keep a couple of “open” spots in your plan, so that there is a bit of room for spontaneity.",
  "image": "picId-117.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 118,
  "name": "Make your bed every day",
  "description": "File this under “things you should be doing anyway”. But really, if you’re not, set yourself this challenge for 30 days and make it a part of your morning routine!",
  "image": "picId-118.svg",
  "type": "unit",
  "categoryId": "3",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "05/11/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 119,
  "name": "Try a capsule wardrobe",
  "description": "Jessica is a huge champion of the capsule wardrobe and in fact, all things slow living. If you’re a capsule wardrobe newbie, be sure to check out her blog and/or her ebook.",
  "image": "picId-119.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 120,
  "name": "Reach out to one new person every day",
  "description": "Even if you’re a hardcore introvert, truth is, you have to put yourself out there if you want your blog/business to shine. Reach out to new people via Instagram, Twitter, emails. Send a fellow blogger a heartfelt email. Interact with your followers on social media. Pitch to a brand. Reach out to a PR person. Just do something every day that puts you and your blog/business out there.",
  "image": "picId-120.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 121,
  "name": "Show up on Instagram stories at least once a day",
  "description": "InstaStories is a fantastic way to connect with your audience. It might take a while, but get comfortable talking to your followers. It’ll build a better relationship with them which in turn will lead to more brand recognition and loyalty.",
  "image": "picId-121.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 122,
  "name": "Publish one post a day on your blog or Instagram or YouTube",
  "description": "Okay, so this isn’t necessarily easy. Creating quality content takes a lot of time and effort, but if you plan for this challenge, it can be done! For inspiration, check out Anna’s (of The Anna Edit) post on how to plan and execute such a challenge.",
  "image": "picId-122.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 123,
  "name": "Eat at least one meal together with your partner/family",
  "description": "Building a life together is about sharing the little things. Coming together at meal times is one of the best ways to connect with your partner/family on a daily basis. And sure, in an ideal world, this should be the norm, but if it’s not, sometimes you just have to get intentional about it.",
  "image": "picId-123.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 124,
  "name": "Call your parents/relatives/old friends",
  "description": "Amongst the many lessons this year has taught us, the value of meaningful human connections is certainly one of the most important ones. Make those calls, and see how someone else lights up at being remembered.",
  "image": "picId-124.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "05/11/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 125,
  "name": "Write a love note to your partner or child",
  "description": "This could be such a cute little thing to do. Small love notes to brighten up your partner or child! Ah, I am smiling just thinking about the joy of doing something like this.",
  "image": "picId-125.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 126,
  "name": "Actively participate in your partner’s hobby",
  "description": "Now sure, you don’t have to do everything together with your partner, but showing active interest in their hobby can only help to improve your personal connection! Find out about their favorite sports team, watch their favorite movies or shows along with them, cook together. Basically, just show up, and let them know that their interests matter to you as well.",
  "image": "picId-126.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 127,
  "name": "Set up 30 surprises for your partner",
  "description": "Again, this does not have to be a big thing. You don’t have to go out and buy 30 different things to surprise your partner. Get creative with your ideas. Buy their favorite bottle of wine. Indulge them with breakfast in bed. Cook their favorite meal for no special reason. Get them their childhood favorite snacks/candy. Purchase that scarf they’ve been lusting over for so many weeks.",
  "image": "picId-127.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 128,
  "name": "Brush your teeth twice a day",
  "description": "It’s so easy and painless but so very hard to do and do well. Dental hygiene is more important than we realize. Food particles in our mouths (especially from processed foods or foods high in sugar) can become a breeding ground for bacteria that impacts not just the health of our teeth, but potentially for the rest of the body as well.",
  "image": "picId-128.svg",
  "type": "unit",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 129,
  "name": "Floss every day",
  "description": "Work your way up to flossing (and flossing thoroughly) every day. You can start with just one tooth on the first day, and then work your way up to two, four, one side, then the other. Whatever gets you flossing.",
  "image": "picId-129.svg",
  "type": "unit",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 130,
  "name": "Take your vitamins",
  "description": "Because we all have nutritional deficiencies (mine are iron, magnesium and vitamin D), especially if our diets aren’t perfect.",
  "image": "picId-130.svg",
  "type": "unit",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "05/11/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 131,
  "name": "Do brain training exercises",
  "description": "The point of brain training is to push your brain to the point of frustration so that your neural connections strengthen. And it can be incredibly difficult. But pick an app and commit to doing the exercises for a given amount of time, every day. Lumosity, Elevate, or Rosetta Stone’s FitBrains are all great choices.",
  "image": "picId-131.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 132,
  "name": "Detox your house",
  "description": "Our houses are filled with toxic and synthetic chemicals. They’re in our beauty products, household cleaning supplies, plastic toys, plastic cookware, dirty electricity and God knows what else. Over the next 30 days, slowly do a home makeover and replace your regular household items with organic, natural ones. ",
  "image": "picId-132.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 133,
  "name": "Take a cold shower",
  "description": "That’s right. When you get up in the morning, head for the shower and turn it to cold. It sounds AWFUL, but  there are many health benefits of taking cold showers, from improved circulation, energy, sleep and workout recovery. Read this person’s account of his cold shower challenge.",
  "image": "picId-133.svg",
  "type": "unit",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 134,
  "name": "Bike",
  "description": "Get on your bike and ride. Every day. Bike to work, bike around town or on hills or on trails.",
  "image": "picId-134.svg",
  "type": "unit",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 135,
  "name": "Take the stairs",
  "description": "For 30 days, refuse to use the elevator.",
  "image": "picId-135.svg",
  "type": "unit",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 136,
  "name": "Whole body challenges",
  "description": "Because focusing on one thing can be boring. Find a 30 day fitness challenge that incorporate lots of exercises.",
  "image": "picId-136.svg",
  "type": "unit",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "05/11/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 137,
  "name": "Brainstorm",
  "description": "This is an easy and fun way to train yourself to think more creatively, an idea from James Altucher’s very entertaining blog. Every day for 30 days, write down 10 or 20 or, for the more ambitious, 50 ideas – for anything. A blog you want to start. Books you’d want to write. Things you would buy if you had a billion dollars. It forces you to stretch your brain and strengthen the idea muscle.",
  "image": "picId-137.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 138,
  "name": "Clean up your digital clutter",
  "description": "Every day, work on something to clean up your digital clutter: your email, your photos, your movies, your social media, passwords, documents. Put systems in place to make it easy to stay digitally organized because you’re only going to keep accumulating content and will need to find a safe home for everything.",
  "image": "picId-138.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 139,
  "name": "Check email once or twice a day",
  "description": "It’s such a distraction and time suck and email management is difficult enough as it is, but it works wonders for your productivity. So for 30 days, try this. Turn your email off on your phone and mobile devices. Pick one or two 30 minute periods during the day to read and respond to email and set an auto responder to let people know of your new email policy. ",
  "image": "picId-139.svg",
  "type": "unit",
  "categoryId": "5",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 140,
  "name": "No cursing",
  "description": "Because, well shit. Oh shit. I just said shit. Shit.",
  "image": "picId-140.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 141,
  "name": "No devices in the bedroom ",
  "description": "Because it’s one of the best ways to improve your sleep.",
  "image": "picId-141.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 142,
  "name": "No fast food",
  "description": "Some of us rarely eat fast food, making this an easy challenge. But it’s part of the daily routine for many others. Is addicting, cheap, and convenient, requiring a total, potentially very difficult shift in meal planning and preparation.",
  "image": "picId-142.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "05/11/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 143,
  "name": "No news",
  "description": "No reading or watching the news. If something newsworthy happens, let someone else tell you about it. The news can be addicting and depressing and just like the things we eat affect our physical health, the information we consume affects us mentally. I would imagine that after the first few days of “news withdrawals”, the process would be quite liberating. And maybe at the end, you’ll have a better process for consuming information in a more healthy and productive way.",
  "image": "picId-143.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 144,
  "name": "No social media",
  "description": "I’m a social media junkie. I check it dozens of times a day, not because I care much about what other people or brands are doing. I do it out of habit. Imagine, then, how much I could accomplish if I didn’t waste all those minutes on Buzzfeed wondering what Game of Thrones character I am.",
  "image": "picId-144.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 145,
  "name": "No TV",
  "description": "There is so much great television out there and I’m a big fan of unwinding with a show. But an hour or two of television every night is an hour or two of time we could spend doing other, more productive things.",
  "image": "picId-145.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "04/01/2022",
  "endDateTime": "05/01/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 146,
  "name": "No caffeine",
  "description": "You might get headaches from the caffeine withdrawals, so be prepared for the symptoms. Even better, reduce your caffeine intake slowly in the week preceding your no caffeine month.",
  "image": "picId-146.svg",
  "type": "unit",
  "categoryId": "4",
  "subCategoryId": null,
  "startDateTime": "04/15/2022",
  "endDateTime": "05/15/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 147,
  "name": "No gossiping",
  "description": "Gossip is so much fun and so very tempting. Especially because it bonds us with other people. But gossip, in essence, is to speak “with the intent of eroding another person’s reputation, image, or standing in the recipient’s eyes”. If you find yourself falling into the too much gossip trap, perhaps it’s time to take a break from the negativity.",
  "image": "picId-147.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "04/10/2022",
  "endDateTime": "05/10/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 1,
  "isPrivate": "false"
 },
 {
  "id": 148,
  "name": "Sex/No sex ",
  "description": "Abstinence is very hard for some. But there are others who are single and can’t get it or are in relationships and could use a little or lot more. Either way, everyone has their reasons for abstaining or going all in (intimacy takes effort!). I’ll let you be the judge of that.",
  "image": "picId-148.svg",
  "type": "unit",
  "categoryId": "2",
  "subCategoryId": null,
  "startDateTime": "04/11/2022",
  "endDateTime": "05/11/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 },
 {
  "id": 149,
  "name": "No internet ",
  "description": "I’m actually not sure how this is feasible for most people for an entire month. I would imagine it would be excruciating. Especially since I do virtually everything online – banking, shopping, communicating, working.",
  "image": "picId-149.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "03/31/2022",
  "endDateTime": "04/30/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 3,
  "isPrivate": "false"
 },
 {
  "id": 150,
  "name": "Learn lucid dreaming ",
  "description": "How amazing would it be aware that you are dreaming? And then have the ability to control your dreams? Instructions for learning to lucid dream in 30 days are here, but be warned, it requires a lot of discipline and steps.",
  "image": "picId-150.svg",
  "type": "unit",
  "categoryId": "1",
  "subCategoryId": null,
  "startDateTime": "03/30/2022",
  "endDateTime": "04/29/2022",
  "targetNumber": null,
  "targetUnit": null,
  "difficultyRating": 2,
  "isPrivate": "false"
 }
]

module.exports = { dataChallenges }